version: '3.8'

services:
  Deep-Live-Cam:
    container_name: Deep-Live-Cam
    image: docker.io/avgradmin/deep-swap:v0.1.2-cuda-12.2
    build:
      context: .
      dockerfile: docker/Dockerfile.cuda12-2  
    environment:
      ## Processor
      - MANY_FACES=false  # true/false
      - frame_processor=face_swapper
      ## Performance
      - max_mem=8
      - threads=4
      - video_encoder=libx265
      - USE_GPU=cuda  # Change to cuda or whatever you need to use. 'false' disables.
      ## Video
      - USE_VIDEO_ARGS=false  # true/false
      - video_quality=0

      # Display
      - DISPLAY=$DISPLAY
    volumes:
      - ./Deep-Live-Cam-Docker:/app
      - ./docker/docker_script.sh:/app/docker_script.sh
      - ./models/.insightface:/root/.insightface
      - ./models/.insightface:/app/.insightface
      - ./models/gfpgan:/app/gfpgan
      - ./models:/app/models
      - ./output:/app/output

      # Display
      - /tmp/.X11-unix:/tmp/.X11-unix 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    runtime: nvidia
    command: [ "/bin/bash", "/app/docker_script.sh" ]
