version: '3.8'

services:
  Deep-Live-Cam:
    container_name: Deep-Live-Cam
    image: docker.io/avgradmin/deep-swap:v0.1.2-cuda-12.2
    build:
      context: .
      dockerfile: docker/Dockerfile.cuda12-2  
    environment:
      ## Output / Inputs
      - DEFAULT_SOURCE=/app/output/source_files
      - DEFAULT_TARGET=/app/output/target_files
      - DEFAULT_OUTPUT=/app/output/output_files/test
      ## Processor
      - MANY_FACES=false  # true/false
      - frame_processor=face_swapper
      ## Performance
      - max_mem=8
      - threads=2
      - video_encoder=libx265
      - USE_GPU=cuda  # Change to cuda or whatever you need to use. 'false' disables.

      ## Video (Only needed cor CLI)
      - USE_VIDEO_ARGS=true  # true/false
      - video_quality=0

      # Display # Linux use 'xhost +' in cli to enable window
      - DISPLAY=$DISPLAY
    volumes:
    # Change according to your setup
      - ./iRoopDeepFaceCam-avgr:/app
      # Do not change below volumes
      - ./output/docker.sh:/app/docker_script.sh
      - ./models/.insightface:/root/.insightface
      - ./models/.insightface:/app/.insightface
      - ./models/gfpgan:/app/gfpgan
      - ./models:/app/models
      - ./models:/app/modules/models
      - ./output:/app/output

      # Display
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    privileged: true # Need for webcam
    runtime: nvidia
    command: [ "/bin/bash", "/app/docker_script.sh" ]
